CREATE TABLE IF NOT EXISTS users
(
    user_ID INT GENERATED ALWAYS AS IDENTITY,
    user_Cookie VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(user_ID)
);

CREATE TABLE IF NOT EXISTS urls
(
    user_ID INT,
    shortURL VARCHAR(100) NOT NULL,
    originalURL VARCHAR(100) NOT NULL UNIQUE,
    isDelete BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_ID) REFERENCES users (user_ID)
);